version: 1.0.10
cache: true
 
interface:
  runCode: true
  agents: true
  webSearch: true
  modelSelect: true
  customWelcome: "Hey {{user.name}}! Welcome to AskTreez"

mcpServers:
  zapier:
    type: sse
    url: https://actions.zapier.com/mcp/sk-ak-7aEBtnMeMGSgg6qTIqe3JspoZV/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
  snowflake:
    type: sse
    url: https://api.centralmind.ai/mcp/sse?server_id=cmat824dg004m920jdzgyslpe&endpoint_key=UVaLT0WNEPrf1uZde8rgXwvvz535JzIpSwH%2FFxrPqBZmycitOwCrR%2BqDRPs8pCZBiOCSpNQp3RwwhMupAKonf3IRbjccLd2ujROY
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
  sf:
    type: sse
    url: https://snowflake-mcp-backend.onrender.com/mcp/c9cda771-0dbf-4637-90ed-b9cf9c975098/sse
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
    initTimeout: 40000
  browser:
    type: sse
    url: https://browserbase.onrender.com/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
  grafana:
    type: sse
    url: https://mcp-grafana.onrender.com/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
  intercom:
    type: sse
    url: https://mcp.intercom.com/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      Authorization: "Bearer ${INTERCOM_API_TOKEN}"
  slack:
    type: stdio
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-slack"
    timeout: 30000
    initTimeout: 20000
    env:
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
      SLACK_TEAM_ID: "${SLACK_TEAM_ID}"
    stderr: inherit
  confluence:
    type: sse
    url: https://mcp-atlassian-snhy.onrender.com/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"
  salesforce:
    type: stdio
    command: npx
    args:
      - -y
      - "@tsmztech/mcp-server-salesforce"
    timeout: 30000
    initTimeout: 20000
    env:
      SALESFORCE_USERNAME: "${SALESFORCE_USERNAME}"
      SALESFORCE_PASSWORD: "${SALESFORCE_PASSWORD}"
      SALESFORCE_TOKEN: "${SALESFORCE_TOKEN}"
      SALESFORCE_INSTANCE_URL: "${SALESFORCE_INSTANCE_URL}"
    stderr: inherit
  gitlab:
    type: sse
    url: https://gitlab-mcp.onrender.com/sse  # Replace with your actual Zapier MCP endpoint
    initTimeout: 20000
  pendo:
    type: sse
    url: https://pendo-mcp.onrender.com/mcp/sse  # Replace with your actual Zapier MCP endpoint
    initTimeout: 20000

    
endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    allowedProviders:
      - openAI
      - anthropic      
      - google
    capabilities:
      - "actions"
      - "execute_code"
      - "artifacts"
      - "tools"
      - "chain"
      - "file_search"
      - "web_search"
      - "ocr"
actions:
  allowedDomains:
    - "treez.io"
    - "onrender.com"
    - "openai.com"
    - "test-api.treez.io"
    - "treezgateway.onrender.com"  
    - "uzvlw67ks9.execute-api.us-west-2.amazonaws.com"  
    - "api.intercom.io"
    - "app.pendo.io"
    - "api.gong.io"
    - "gsheet-search.onrender.com"

speech:
  speechTab:
    conversationMode: true
    advancedMode: true
  textToSpeech:
    engineTTS: "external"
    voice: "alloy"
    languageTTS: "en"
    automaticPlayback: true
    playbackRate: 1.0
    cacheTTS: true
  tts:
    openai:
      apiKey: '${TTS_API_KEY}'
      model: 'gpt-4o-mini-tts'
      voices: ['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer']
      
webSearch:
  # Search Provider Configuration
  serperApiKey: "${SERPER_API_KEY}"
  searchProvider: "serper" # Options: "serper", "searxng"
 
  # Scraper Configuration
  firecrawlApiKey: "${FIRECRAWL_API_KEY}"
  scraperType: "firecrawl" # Options: "firecrawl", "serper"
 
  # Reranker Configuration
  cohereApiKey: "${COHERE_API_KEY}"
  rerankerType: "cohere" # Options: "jina", "cohere"
 
  # General Settings
  scraperTimeout: 7500 # Timeout in milliseconds for scraper requests (default: 7500)
  safeSearch: 0 # Options: 0 (OFF), 1 (MODERATE - default), 2 (STRICT)    

balance:
  enabled: true                # Enable token credit balances for users
  startBalance: 2000000          # Initial tokens credited upon registration
  autoRefillEnabled: true     # Enable automatic token refills
  refillIntervalValue: 1      # Numerical value for refill interval
  refillIntervalUnit: "hours"   # Time unit for refill interval (days, hours, etc.)
  refillAmount: 1000000          # Tokens added during each refill
