version: 1.0.10
cache: true
 
interface:
  runCode: true
  agents: true
  modelSelect: true
  customWelcome: "Hey {{user.name}}! Welcome to AskTreez"

mcpServers:
  zapier:
    type: sse
    url: https://actions.zapier.com/mcp/sk-ak-7aEBtnMeMGSgg6qTIqe3JspoZV/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
  snowflake:
    type: sse
    url: https://api.centralmind.ai/mcp/sse?server_id=cmat824dg004m920jdzgyslpe&endpoint_key=NwQwvt84OR0Th4U3kdXyZDPrnDESv4ZeU8TLlWUQW5jSDu05KCO8jxlTtQrrkHp1t%2BkiSy01l6O6sC62Pu3Zwa7wmIECrtuKf9Qh
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment

      
endpoints:
  agents:
    recursionLimit: 50
    maxRecursionLimit: 100
    disableBuilder: false
    allowedProviders:
      - openAI
      - anthropic      
      - google
    capabilities:
      - "actions"
      - "execute_code"
      - "artifacts"
      - "tools"
      - "chain"
      - "file_search"
      - "web_search"
      - "ocr"
actions:
  allowedDomains:
    - "treez.io"
    - "onrender.com"
    - "openai.com"
    - "test-api.treez.io"
    - "treezgateway.onrender.com"  
    
webSearch:
  # Search Provider Configuration
  serperApiKey: "${SERPER_API_KEY}"
  searchProvider: "serper" # Options: "serper", "searxng"
 
  # Scraper Configuration
  firecrawlApiKey: "${FIRECRAWL_API_KEY}"
  scraperType: "firecrawl" # Options: "firecrawl", "serper"
 
  # Reranker Configuration
  cohereApiKey: "${COHERE_API_KEY}"
  rerankerType: "cohere" # Options: "jina", "cohere"
 
  # General Settings
  scraperTimeout: 7500 # Timeout in milliseconds for scraper requests (default: 7500)
  safeSearch: 0 # Options: 0 (OFF), 1 (MODERATE - default), 2 (STRICT)    

balance:
  enabled: true                # Enable token credit balances for users
  startBalance: 200000          # Initial tokens credited upon registration
  autoRefillEnabled: true     # Enable automatic token refills
  refillIntervalValue: 30      # Numerical value for refill interval
  refillIntervalUnit: "days"   # Time unit for refill interval (days, hours, etc.)
  refillAmount: 100000          # Tokens added during each refill
