version: 1.0.8
cache: true
 
interface:
  runCode: false
  modelSelect: false
  customWelcome: "Hey {{user.name}}! Welcome to AskTreez"

mcpServers:
  zapier:
    type: sse
    url: https://actions.zapier.com/mcp/sk-ak-7aEBtnMeMGSgg6qTIqe3JspoZV/sse  # Replace with your actual Zapier MCP endpoint
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
  snowflake:
    type: sse
    url: https://api.centralmind.ai/mcp/sse?server_id=cmat824dg004m920jdzgyslpe&endpoint_key=iMtONYubJXbL5vK2vDcgzvpaHMKiEOqlCBuRZyLEC0NeAgIR0JYqDCzqKoonhXbA7QgKpx9jFXwWNCSS34AJJPJUtEsVufBmahPv
    headers:
      X-User-ID: "{{LIBRECHAT_USER_ID}}"  # This enables per-user assignment
      
endpoints:
  agents:
    disableBuilder: true

balance:
  enabled: true                # Enable token credit balances for users
  startBalance: 200000          # Initial tokens credited upon registration
  autoRefillEnabled: true     # Enable automatic token refills
  refillIntervalValue: 30      # Numerical value for refill interval
  refillIntervalUnit: "days"   # Time unit for refill interval (days, hours, etc.)
  refillAmount: 100000          # Tokens added during each refill
